site_name: OpenShift Examples
site_url: https://openshift-tiger-team.github.io/openshift-examples
theme:
  name: material
  logo: images/ocp.png
  favicon: images/favicon_io/favicon.ico
  font:
    text: Red Hat Text
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.instant
nav:
  - Home: index.md
  - Install: install/install.md
  - Networking: networking/networking.md
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
plugins:
  - include-markdown
  - macros
  - search

extra:
  ocp_version: 4.19
