apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: 2-eth-bond-active-backup-vlan
spec:
  nodeSelector:
    kubernetes.io/hostname: <hostname>
  desiredState:
    interfaces:
      - name: <devicename>
        type: ethernet
        state: up
        mac-address: <macaddress>
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: <devicename2>
        type: ethernet
        state: up
        mac-address: <macaddress2>
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: bond1
        type: bond
        state: up
        link-aggregation:
          mode: active-backup
          port:
            - <devicename>
            - <devicename2>
          options:
            miimon: '100'
            primary: <devicename>
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: bond1.<vlanid>
        type: vlan
        state: up
        vlan:
          base-iface: bond1
          id: <vlanid>
        ipv4:
          enabled: true
          address:
            - ip: <ipaddress>               
              prefix-length: <prefixlength> # 24
          dhcp: false
        ipv6:
          enabled: false