apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: 2-eth-bond-trunk-ovs-bridge-trunk-cudn
spec:
  nodeSelector:
    kubernetes.io/hostname: ocp2
  desiredState:
    interfaces:
      - name: eno1
        type: ethernet
        state: up
        mac-address: 7c:c2:c6:45:ae:85
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: eno2
        type: ethernet
        state: up
        mac-address: 1c:69:7a:61:d6:9d
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: bond1
        type: bond
        state: up
        link-aggregation:
          mode: active-backup
          port:
            - eno1
            - eno2
          options:
            miimon: '100'
            primary: eno1
        ipv4:
          enabled: false
        ipv6:
          enabled: false
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-trunk-nncp
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: ovs-bridge-trunk
        type: ovs-bridge
        state: up
        bridge:
          port:
            - name: bond1
          allow-extra-patch-ports: true
          options:
            stp: false # DO NOT ENABLE STP unless you know what you are doing!
    ovn:
      bridge-mappings:
        - localnet: localnet-bridge-trunk
          bridge: ovs-bridge-trunk
          state: present
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
 name: vlan4-cudn
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["default", "other"] 
  network:
    topology: Localnet
    localnet:
      role: Secondary
      physicalNetworkName: localnet-bridge-trunk
      vlan:
        mode: Access
        access:
          id: 4
      subnets:
        - "10.4.0.0/24"
      excludeSubnets:
        - "10.4.0.0/31"       # excludes 10.4.0.0 – 10.4.0.1
        - "10.4.0.255/32"     # excludes 10.4.0.255
      ipam:
        mode: Enabled         # DEFAULT!
        lifecycle: Persistent
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
 name: vlan37-cudn
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["default", "project1", "project2"] 
  network:
    topology: Localnet
    localnet:
      role: Secondary
      physicalNetworkName: localnet-bridge-trunk
      vlan:
        mode: Access
        access:
          id: 37
      ipam:
        mode: Disabled
