apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-trunk-nncp
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: ovs-bridge-trunk
        type: ovs-bridge
        state: up
        bridge:
          port:
            - name: bond1
          allow-extra-patch-ports: true
          options:
            stp: false # DO NOT ENABLE STP unless you know what you are doing!
    ovn:
      bridge-mappings:
        - localnet: localnet-bridge-trunk
          bridge: ovs-bridge-trunk
          state: present